### ISSUE TITLE
mimeapps.list get overriden and makes activation fail

### ISSUE THREAD

**Issue by M-Gregoire** [nix-community/home-manager#1213]
Hi,

I've been trying out `xdg.mimeApps` and I love the idea. Overall, it works really well except some software override `~/.config/mimeapps.list` very frequently (I'm guessing Thunar) which not only lead to unwanted association but also make the next home-manager activation fail:
```
Hostname.......> <DATE> Hostname hm-activate-user[28434]: Activating home-manager configuration for user
Hostname.......> <DATE> Hostname hm-activate-user[28434]: Starting home manager activation
Hostname.......> <DATE> Hostname hm-activate-user[28434]: Activating checkFilesChanged
Hostname.......> <DATE> Hostname hm-activate-user[28434]: Activating checkLinkTargets
Hostname.......> <DATE> Hostname hm-activate-user[28434]: Existing file '/home/user/.config/mimeapps.list' is in the way
Hostname.......> <DATE> Hostname hm-activate-user[28434]: Please move the above files and try again or use -b <ext> to move automatically.
```

I've tried using an `home.activation` script in order to delete the `mimeapps.list` but unfortunately it seems those scripts are executed after home-manager tries to create the symlink.

Looking at past issues, I noticed I'm not the first person wondering (https://github.com/rycee/home-manager/pull/834#issuecomment-530527582) but I couldn't find a solution to this issue (apart from using the `-b` option every time, which is far from ideal).

Is there any way to either 
- Make the file read only (which as far as I know doesn't break anything) 
- Or run `rm ~/.config/mimeapps.list` **before** every home-manager activation
? 

Thank you for any help you might provide.

Unrelated question for @rycee (As I don't believe I should open an issue for this): Have you considered using Github sponsor or another type of donation for your work on `home-manager`? I'm sure some people would gladly try to support you financially for the time you spend on it.

**Comment by rycee** [comment]
I think the simplest would be to add
```
xdg.configFile."mimeapps.list".force = true;
```
to your configuration. This will make HM silently overwrite any existing file at that path and would work similar your second alternative.

Since `mimeapps.list` is a symlink there is no way to make it read only so the first alternative would not work.

About donations, it's very kind of you to ask 🙂 I haven't reflected on it before but I think it's unlikely that I would look for any sponsorship. If I were to attempt getting any money out of my work in the Nix ecosystem then I think it would be in the form of consulting work. For donations I suggest [NixOS foundation](https://nixos.org/donate.html), which indirectly benefits me as well since I enjoy the conferences 😉

**Comment by piegamesde** [comment]
I found out that my `mimeapps.list` symlink is simply replaced with the resolved file, without any modification. I think it would be safe to overwrite files with a symlink of identical content without warning in those cases.

**Comment by piegamesde** [comment]
Also, the error message could be improved: Instead of `Existing file '~/.config/mimeapps.list' is in the way`, it could tell which file wants to overwrite: `Existing file '~/.config/mimeapps.list' is in the way of /nix/store/foo/mimeapps.list`. The user can then easily diff both paths and take respective actions. (But maybe this belongs to a separate issue?)

**Comment by NorfairKing** [comment]
@plegamesde Thanks for pushing this forward. Please ping me if there's anything I can do to help this along.

**Comment by piegamesde** [comment]
@NorfairKing You can review and try out #1250. I'm using it for months now, without any issues and it removed all false positives while activating that I had before.

**Comment by NorfairKing** [comment]
I'm using this instead for now:
```
xdg.configFile."mimeapps.list".force = true;
```
but I see nothing wrong with #1250

**Comment by teto** [comment]
I had submitted a patch > 5 years ago to xdg-utils so that mimeapps.list is rewritten correctly. Maybe someone could push for sthg similar again (or we could install a patched version). The symlink being erase was an issue even before using HM.
#1250 feels a bit overkill as the issue mostly concerns mime.utils

**Comment by piegamesde** [comment]
@teto You could try re-submitting your patch as [merge request](https://gitlab.freedesktop.org/xdg/xdg-utils/-/merge_requests). Apart from that, there's a (rather branched) thread ["Taking over xdg-utils"](https://lists.freedesktop.org/archives/xdg/2019-December/014210.html) on the mailing list about the maintenance of the project and a Python rewrite.

Installing a patched version of xdg-utils would be fine for me, I'd be glad to try it out if packaged in Nix.

Personally, I wouldn't say my pull request is "overkill", as it does fix the issue in the general case with misbehaving applications without harming all others. Nevertheless, I'd be willing to make it opt-in on a per file base similar to `xdg.configFile.*filename*.force`. (Naming proposals welcome). But maybe we should move that discussion on to the PR itself

**Comment by teto** [comment]
thanks for the link to the mailing list. Last merged MR was 6 months ago so not dead yet but a few rotting PR .

this is the patch, it might be faulty since then:
```
diff --git a/scripts/xdg-mime.in b/scripts/xdg-mime.in
index 0e567c7..0038b0b 100644
--- a/scripts/xdg-mime.in
+++ b/scripts/xdg-mime.in
@@ -245,9 +245,13 @@ make_default_generic()
     xdg_config_home="$XDG_CONFIG_HOME"
     [ -n "$xdg_config_home" ] || xdg_config_home="$HOME/.config"
     default_file="$xdg_config_home/mimeapps.list"
+    out_file="$default_file"
     DEBUG 2 "make_default_generic $1 $2"
     DEBUG 1 "Updating $default_file"
     [ -f "$default_file" ] || touch "$default_file"
+	if [ -L "$default_file" ]; then out_file=$(readlink -f "$default_file"); fi
+
+    DEBUG 2 "Writing to $out_file"
     awk -v mimetype="$2" -v application="$1" '
     BEGIN {
         prefix=mimetype "="
@@ -295,7 +299,7 @@ make_default_generic()
             blanks--
         }
     }
-' "$default_file" > "${default_file}.new" && mv "${default_file}.new" "$default_file"
+' "$default_file" > "${default_file}.new" && mv "${default_file}.new" "$out_file"
 }
 
 search_desktop_file()
```

**Comment by NorfairKing** [comment]
Still relevant

**Comment by NorfairKing** [comment]
Definitely still relevant.

**Comment by ilkecan** [comment]
> Since mimeapps.list is a symlink there is no way to make it read only so the first alternative would not work.

How about using `mount --bind` instead of creating symlinks[1]? I am not really familiar with internals of home-manager; would this be possible? I know home-manager can be used without root but maybe this could be done when using it as a NixOS module.

[1] https://unix.stackexchange.com/a/597189

**Comment by ilkecan** [comment]
Even if it is possible, this is an ugly hack. So, I want to withdraw my suggestion.

**Comment by nerosnm** [comment]
I'm not sure I agree that this is resolved. I'm finding that if something causes the symlink `~/.config/mimeapps.list` to be overwritten (such as changing a default application in the GNOME settings), now home-manager activation silently succeeds without touching the overwritten file. Worse, even if I `rm ~/.config/mimeapps.list`, home-manager does not create a new symlink unless I change something inside `config.xdg.mimeApps` and activate again.

**Comment by nerosnm** [comment]
What details would you like? I have a configuration as follows:

```nix
{
  xdg.configFile."mimeapps.list".force = true;
  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      "text/html" = "firefox.desktop";
      # others...
    };
    associations.added = {
      "x-scheme-handler/mailto" = "thunderbird.desktop";
      # others...
    };
  };
}
```

I use the home-manager NixOS module, and so when I run `nixos-rebuild switch`, a symlink is created at `~/.config/mimeapps.list` to a file with the expected contents. But if I open GNOME settings and go to "Default Applications" and change (for example) the default application for "Web" to Chromium, that symlink is overwritten by a regular file with the contents updated to include (for example) the line `text/html=chromium-browser.desktop` under `[Default Applications]`.

If I then run `nixos-rebuild switch` again, nothing happens to that file; it is not deleted, replaced with a symlink, moved to a `~/.config/mimeapps.list.backup`, or anything else. If I run `rm ~/.config/mimeapps.list`, verify that the file has been deleted and not replaced by GNOME settings, and then `nixos-rebuild switch` again, no new symlink or file is created.

The only thing that will cause a symlink to be created there again is to edit my configuration to make some change to the `xdg.mimeApps` config option, like setting `"text/html" = "chromium-browser.desktop";`. Now running `nixos-rebuild switch` will create the symlink again (this is the first time since touching the GNOME settings that `nixos-rebuild switch` will cause the `home-manager-soren.service` unit to be restarted). I can then change the setting back to firefox, and running `nixos-rebuild switch` again will finally produce the system state I wanted.

**Comment by piegamesde** [comment]
I cannot reproduce any of your issues on my machine, so I suggest opening a new bug report for it.

**Comment by jheidbrink** [comment]
I see the same behaviour and I'm wondering how applications can modify the `mimeapps.list` at all, given that it's a link to a readonly file in the Nix store.

**Comment by lowgos** [comment]
The issue persists, I got a fresh config and I get the issue twice a week on boot.
The overwrite rule seems to fix the problem but I don't understand how a symlink to the read-only file can be overwriting silently by a program either.
Really strange.

**Comment by Fran314** [comment]
I also run into this issue frequently, I don't understand why the issue is closed without a fix

**Comment by f0rdprefect** [comment]
I just ran into this as well. Looks like firefox exhibits the same behavior - moving the symlinked file to .backup which then will make the backup fail.
