### ISSUE TITLE
bug: Activation fails on Darwin due to missing `readlink` `-m` option

### ISSUE THREAD

**Issue by ereslibre** [nix-community/home-manager#3516]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Trying to activate my Home Manager, I'm seeing the following error:

```
...
copying path '/nix/store/59xjikhmv1vzcki7143a6ir5cpkzgm91-home-manager-generation' from 'https://workstations.cachix.org/'...
readlink: illegal option -- m
usage: readlink [-fn] [file ...]
usage: dirname string [...]
Starting Home Manager activation
/nix/store/59xjikhmv1vzcki7143a6ir5cpkzgm91-home-manager-generation/bin/home-manager-generation: line 68: nix-build: command not found
...
```

The corresponding CI run [can be found here](https://github.com/ereslibre/dotfiles/actions/runs/3763326552/jobs/6396768328#step:5:865).

I believe the issue boils down to:

https://github.com/nix-community/home-manager/blob/886675991b643b701a33f533443db165c70692d1/modules/home-environment.nix#L691

Given that on MacOS `readlink` has no `-m` option.

### System information

```markdown
- system: `"x86_64-darwin"`
- host os: `Darwin 22.2.0, macOS 10.16`
- multi-user?: `yes`
- sandbox: `no`
- version: `nix-env (Nix) 2.12.0`
- channels(root): `"nixpkgs"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by rycee** [comment]
Thanks for the report, should be fixed in master now.

**Comment by ereslibre** [comment]
Thanks to you @rycee!

**Comment by bestlem** [comment]
This seems not to be complete.

My generated activate includes bare readlinks

```
setupLaunchAgents() {
  local oldDir newDir dstDir domain err
  oldDir=""
  err=0
  if [[ -n "${oldGenPath:-}" ]]; then
    oldDir="$(readlink -m "$oldGenPath/LaunchAgents")" || err=$?
    if (( err )); then
      oldDir=""
    fi
  fi
...
```
and
```
export PATH="/nix/store/n0k8njvgg6yjapkl81rm821s9vx0qrwb-bash-5.2-p15/bin:/nix/store/gvl9w6c5q83nd4svz5v5hqhgfzlcpl3y-coreutils-9.1/bin:/nix/store/pnp0lkyjhrhl7vj0fgrpx80zzzmnkqi6-diffutils-3.8/bin:/nix/store/x080znwmkginz9xb1qchm5dd188m59hg-findutils-4.9.0/bin:/nix/store/fhgm0ly5k1nx277ihmp9fpdgzw73yxjn-gettext-0.21/bin:/nix/store/8j799mid9ai29hg4s4xifx3yn1x1qply-gnugrep-3.7/bin:/nix/store/vjnvxrpi26aigy96fvcfwjx5y5j18h7r-gnused-4.9/bin:/nix/store/n7l5af9vqrjsxzlba
```

and several others,

There is no simple complete minimal example of using flakes on macOS and home-manage that I can find so I have had to tweak things together bny copying from bits.

The flake  is

[t.txt](https://github.com/nix-community/home-manager/files/10677692/t.txt)

**Comment by ncfavier** [comment]
What issue are you reporting exactly? Also your activation script suggests that you are not using the latest Home Manager, please try updating first.

**Comment by ereslibre** [comment]
> What issue are you reporting exactly? Also your activation script suggests that you are not using the latest Home Manager, please try updating first.

I think the issue @bestlem is reporting is that we didn't fix enough `readlink` calls to use the nix version of it (instead of the environment one).

`readlink` on darwin only accepts `-fn`; so all `readlink` calls in home-manager that are susceptible of being called from within Darwin need to be scoped to nix (as we did with https://github.com/nix-community/home-manager/blob/c8f6322303486ab597be92f4b815969e1446438f/modules/home-environment.nix#L690).

Looking at https://github.com/nix-community/home-manager/search?q=readlink, there are other occurences that are not scoped to use `${pkgs.coreutils}/bin/dirname`.

**Comment by ereslibre** [comment]
I think a PR is welcome and hopefully should be a low hanging fruit.

**Comment by ncfavier** [comment]
> by trying to find it on the PATH.

>     export PATH="/nix/store/n0k8njvgg6yjapkl81rm821s9vx0qrwb-bash-5.2-p15/bin:/nix/store/gvl9w6c5q83nd4svz5v5hqhgfzlcpl3y-coreutils-9.1/bin:/nix/store/pnp0lkyjhrhl7vj0fgrpx80zzzmnkqi6-diffutils-3.8/bin:/nix/store/x080znwmkginz9xb1qchm5dd188m59hg-findutils-4.9.0/bin:/nix/store/fhgm0ly5k1nx277ihmp9fpdgzw73yxjn-gettext-0.21/bin:/nix/store/8j799mid9ai29hg4s4xifx3yn1x1qply-gnugrep-3.7/bin:/nix/store/vjnvxrpi26aigy96fvcfwjx5y5j18h7r-gnused-4.9/bin:/nix/store/n7l5af9vqrjsxzlba

coreutils is in there, I don't see a problem here.

Could you please post an error log?

**Comment by bestlem** [comment]
I am new to nix so all I have is the output of activate (which is the same as the original bug)
```
./result/activate .
readlink: illegal option -- m
usage: readlink [-fn] [file ...]
usage: dirname string [...]
Starting Home Manager activation
```

I would note that the fix for the first case did not alter the PATH and had to be fixed by calling readlink etc explicitly.

So there is an issue 

It might just be the line setting PATH in activate which ad the dirname and realpath at the end which is
```
export PATH="/nix/store/n0k8njvgg6yjapkl81rm821s9vx0qrwb-bash-5.2-p15/bin:/nix/store/gvl9w6c5q83nd4svz5v5hqhgfzlcpl3y-coreutils-9.1/bin:/nix/store/pnp0lkyjhrhl7vj0fgrpx80zzzmnkqi6-diffutils-3.8/bin:/nix/store/x080znwmkginz9xb1qchm5dd188m59hg-findutils-4.9.0/bin:/nix/store/fhgm0ly5k1nx277ihmp9fpdgzw73yxjn-gettext-0.21/bin:/nix/store/8j799mid9ai29hg4s4xifx3yn1x1qply-gnugrep-3.7/bin:/nix/store/vjnvxrpi26aigy96fvcfwjx5y5j18h7r-gnused-4.9/bin:/nix/store/n7l5af9vqrjsxzlbaiyzkkjp9qrcpmfc-ncurses-6.3-p20220507/bin:$(dirname $(readlink -m $(type -p nix-env)))"
```

**Comment by ncfavier** [comment]
The `activate` script you posted has

```
:$(dirname $(readlink -m $(type -p nix-env)))"
```

which indicates that the fix for this issue (https://github.com/nix-community/home-manager/commit/d7eee202e597bc7789498a8664082cf0ffedaa8f) has not been applied.

Please update your home-manager input:

```sh
nix flake lock --update-input home-manager
```

**Comment by bestlem** [comment]
Ok that works 

Sorry for the issue I am learning nix and finding no complete up to date examples so I am cargo copying from people's configurations and they are pre this nug fix although I thought I had nixpkgs-latest and installed in mid January.

**Comment by ereslibre** [comment]
Thanks @ncfavier!
