### ISSUE TITLE
bug: download of nmd fails, because  https://git.sr.ht/ is down

### ISSUE THREAD

**Issue by asmundo** [nix-community/home-manager#4879]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

The certificate on git.sr.ht is not up to date. This cause download of tar to fail I suspect. Chrome reports:

```
git.sr.ht
  Your connection to this site is not  secure.You should not enter any sensitive information on this site (for example, passwords or credit cards), because it could be stolen by attackers.
```
  
Suspect this is the reason for: 

  
```
% sudo nixos-rebuild switch 
building Nix...
building the system configuration...

warning: unable to download 'https://git.sr.ht/~rycee/nmd/archive/f18defadcc25e69e95b04493ee02682005472255.tar.gz': Timeout was reached (28); retrying in 300 ms
warning: unable to download 'https://git.sr.ht/~rycee/nmd/archive/f18defadcc25e69e95b04493ee02682005472255.tar.gz': Timeout was reached (28); retrying in 621 ms
```

### System information

```markdown
The output inconsistent as this is triggered as I want to upgrade fom 23.05 to 23.11.

% nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.69, NixOS, 23.05 (Stoat), 23.05.5529.2c9c58e98243`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"home-manager-23.11, nixos-23.11.2728.6723fa4e4f1a"`
 - channels(aos): `"home-manager-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by asmundo** [comment]
@rycee is the patched version available on github?

**Comment by thefossguy** [comment]
This is because sr.ht is down: https://status.sr.ht/

That said, I would love for @rycee to have a mirror of these critical repositories available on GitHub (preferably, since nixpkgs is here too) or GitLab.

**Comment by ldesgoui** [comment]
`manual.{html,manpages,json}.enable = false;` to bypass the issue for now

https://github.com/nix-community/home-manager/blob/e13aa9e287b3365473e5897e3667ea80a899cdfb/modules/manual.nix#L62-L67

**Comment by D3vil0p3r** [comment]
> This is because sr.ht is down: https://status.sr.ht/
> 
> That said, I would love for @rycee to have a mirror of these critical repositories available on GitHub (preferably, since nixpkgs is here too) or GitLab.

It is a very good idea.

**Comment by boozedog** [comment]
@ldesgoui 

> `manual.{html,manpages,json}.enable = false;` to bypass the issue for now
> 
> https://github.com/nix-community/home-manager/blob/e13aa9e287b3365473e5897e3667ea80a899cdfb/modules/manual.nix#L62-L67

I am trying to run `nix-shell '<home-manager>' -A install` ... can I somehow pass a command line argument to this command to bypass?

**Comment by dghubble** [comment]
sr.ht has had more issues affecting home-manager than the status page would suggest https://github.com/nix-community/home-manager/issues/4024

**Comment by asmundo** [comment]
@rycee thanks for your contributions! The below is just a suggestion to make home-manager an even better experience. 

Looking at https://status.sr.ht/. I can see that this site do not currently handle large updates without downtime. For home-manager that is constantly being installed/updated by users this will create issues(noise) every time. I my opinion for home-manager to be  considered stable this is not optimal. @rycee please consider making a mirror on something with higher uptime statistics.

**Comment by SuperSandro2000** [comment]
If the wouldn't be using [fetchTarball](https://github.com/nix-community/home-manager/blob/e13aa9e287b3365473e5897e3667ea80a899cdfb/docs/default.nix#L12) but flake inputs, we could just spin up a mirror and tell people to use that and no interaction from maintainers would be required. :(

**Comment by rycee** [comment]
Switched to an alternative source URL for the time being. Will switch to a more permanent solution later. In any case, this issue should hopefully be resolved. Please comment if there are any additional issues.

**Comment by lovesegfault** [comment]
I'm getting issues with the new URL now :/

```
warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 314 ms
warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 687 ms
warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 1336 ms
warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 2653 ms
```

**Comment by rycee** [comment]
@lovesegfault Hmm, had a quick look in the log and overall it looks OK, there are successful fetches every minute since I published it. Do you consistently get the timeout? The server is hosted by Hetzner in Germany and it's networking has been very stable in my experience.

**Comment by sumnerevans** [comment]
It's working for me (in Denver)

**Comment by lovesegfault** [comment]
It's working again now, must have been a blip :)

**Comment by sanerdsher** [comment]
@rycee, please, reopen this issue. Commit 93e804e7f8a1eb88bde6117cd5046501e66aa4bd didn't fix anything for me. Logs:

```
Jan 11 19:33:23 laptop nixos-rebuild-start[49213]: warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 281 ms
Jan 11 19:35:34 laptop nixos-rebuild-start[49213]: warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 564 ms
Jan 11 19:37:46 laptop nixos-rebuild-start[49213]: warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 1268 ms
Jan 11 19:39:56 laptop nixos-rebuild-start[49213]: warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 2540 ms
Jan 11 19:42:12 laptop nixos-rebuild-start[49213]: warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 5545 ms
Jan 11 19:44:27 laptop nixos-rebuild-start[49213]: warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 10640 ms
Jan 11 19:46:46 laptop nixos-rebuild-start[49213]: warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 20684 ms
Jan 11 19:49:18 laptop nixos-rebuild-start[49213]: warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 35643 ms
Jan 11 19:52:06 laptop nixos-rebuild-start[49213]: warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 78212 ms
Jan 11 19:55:34 laptop nixos-rebuild-start[49213]: warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 162338 ms
Jan 11 20:00:25 laptop nixos-rebuild-start[49213]: warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 258511 ms
Jan 11 20:06:54 laptop nixos-rebuild-start[49213]: warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 710040 ms
Jan 11 20:20:54 laptop nixos-rebuild-start[49213]: warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 1115204 ms
Jan 11 20:41:43 laptop nixos-rebuild-start[49213]: warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 2581120 ms
Jan 11 21:26:55 laptop nixos-rebuild-start[49213]: warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 4303112 ms
```

Thank you in advance.

**Comment by lovesegfault** [comment]
Also seeing errors on another system now

**Comment by rycee** [comment]
Ok, that's unfortunate. I wasn't aware that Hetzner had such poor peering. In any case, will create a PR for including the packages in Nixpkgs tomorrow. Hopefully the Nix cache has better reach.

**Comment by sigprof** [comment]
Apparently https://rycee.net/ is not reachable from Russian IP addresses (tried several providers — there is just no response to the TCP connection to port 443, even though `traceroute --icmp rycee.net` can reach the server, and plain `traceroute rycee.net` reaches `static.213-239-254-10.clients.your-server.de`, which is the host just before the server in `traceroute --icmp`).  It's not obvious which side blocks the HTTPS access.

If the file can be obtained through other means, you can use `nix-prefetch-url --unpack --name source file:///path/to/nmd.tar.gz` as a workaround for not having direct access.

**Comment by ArtemChandragupta** [comment]
I am also in Russia and have this scary problem. Any progress or working workarounds? @sigprof 

```
[artem@nixos:~/Nix]$ sudo nixos-rebuild switch --flake ~/Nix
[sudo] password for artem: 
building the system configuration...
error (ignored): error: SQLite database '/root/.cache/nix/eval-cache-v5/f6ebb467a9125f2971196bb8e88204bd7ee22a93b51d1ffc828c1beaecb8b7d9.sqlite' is busy
warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 291 ms
warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 621 ms
warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 1223 ms
warning: error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28); retrying in 2131 ms
error:
       … while calling the 'head' builtin

         at /nix/store/0g53xyh39z3y90p4d8r341wbqyjy1zhl-source/lib/attrsets.nix:960:11:

          959|         || pred here (elemAt values 1) (head values) then
          960|           head values
             |           ^
          961|         else

       … while evaluating the attribute 'value'

         at /nix/store/0g53xyh39z3y90p4d8r341wbqyjy1zhl-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: unable to download 'https://rycee.net/nmd.tar.gz': Timeout was reached (28)
```

**Comment by sigprof** [comment]
Also apparently on *some* Russian ISPs https://rycee.net/ is accessible over IPv6, but not over IPv4; this might not be universal across all ISPs though, and not all ISPs offer IPv6.

**Comment by ArtemChandragupta** [comment]
After the update, the link did not change and rycee.net itself is also unavailable. Can you tell me when approximately the problem will be solved using standard means and what can be done now?

I would be very glad for any help or hint, because it’s sad to sit without the ability to update the configuration

![swappy-20240113_134636](https://github.com/nix-community/home-manager/assets/90765302/0299ec73-64a1-4b87-a65c-ec8a59fc0bec)

**Comment by rycee** [comment]
@ArtemChandragupta You can download the tarball from https://github.com/nix-community/home-manager/issues/4879#issuecomment-1889311001 then follow the instructions in https://github.com/nix-community/home-manager/issues/4879#issuecomment-1888917048

**Comment by ArtemChandragupta** [comment]
Thank you very much, it worked for me. I'm still new to NixOS, and I often find it difficult to understand things like nix-prefetch-url.

Could you please tell me how I can cancel this command after the link to this file appears in nixpkgs, as I understand it is planned?

**Comment by wch** [comment]
I'm having problems reaching https://git.sr.ht, and I'm in the US.  This is what I see:

```
❯ home-manager switch     
warning: error: unable to download 'https://git.sr.ht/~rycee/nmd/archive/824a380546b5d0d0eb701ff8cd5dbafb360750ff.tar.gz': Timeout was reached (28); retrying in 325 ms
```


I tried downloading the tarball from https://github.com/nix-community/home-manager/issues/4879#issuecomment-1889311001 and running this command from https://github.com/nix-community/home-manager/issues/4879#issuecomment-1888917048:

```
❯ nix-prefetch-url --unpack --name source file:///Users/winston/Downloads/nmd.tar.gz
path is '/nix/store/jjhdi74bxxlihnfdrpqha39019xj5c4f-source'
123pvsnwnha0zivk77yzdvqakn96l17n8lwa78s2h1njlgkw0ng2
```

but even after I do that, I still get the same error when I run `home-manager switch`. I think maybe the downloaded file has a different hash than what my system is looking for? Any help would be appreciated -- I'd really like to be able to change my user configuration on my computer again.

**Comment by ArtemChandragupta** [comment]
@wch have you updated flake.nix? I done this, also I fetched nmd.tar.gz directly from rycee's comment.

**Comment by wch** [comment]
@ArtemChandragupta I'm not sure if this part is what you have in mind, but my flake.nix has this. I haven't made any changes to it recently.

```
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
```

**Comment by ArtemChandragupta** [comment]
@wch I talk about command nix flake update to update the versions of files that your sistem fetches and links to them.

I think that you haven`t done it because your  nmd.tar.gz is on https://git.sr.ht/... 
It is the old link before 12.01

**Comment by rycee** [comment]
Hopefully it should be resolved now, the package is now taken from the binary cache.
