### ISSUE TITLE
bug: Failed to start unit gpg-agent.service

### ISSUE THREAD

**Issue by DamienCassou** [nix-community/home-manager#6308]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

Since I switched to Debian stable yesterday, I'm getting errors at the end of `home-manager switch`:

```
Stopping units: borgmatic.timer, caffeine.service, clipmenu.service, emacs.service, emacs.socket, git-maintenance@daily.timer, git-maintenance@hourly.timer, git-maintenance@weekly.timer, gpg-agent-ssh.socket, gpg-agent.service, gpg-agent.socket, mpd.service, signaturepdf.service, syncthing.service, systembus-notify.service, tray.target
Starting units: borgmatic.timer, caffeine.service, clipmenu.service, emacs.service, emacs.socket, git-maintenance@daily.timer, git-maintenance@hourly.timer, git-maintenance@weekly.timer, gpg-agent-ssh.socket, gpg-agent.service, gpg-agent.socket, mpd.service, signaturepdf.service, syncthing-init.service, syncthing.service, systembus-notify.service, tray.target, vdirsyncer.timer
Error: Error switching

Caused by:
    0: Failed to perform post-reload tasks
    1: Failed to start unit gpg-agent.service
    2: org.freedesktop.systemd1.OnlyByDependency: Operation refused, unit gpg-agent.service may be requested by dependency only (it is configured to refuse manual start/stop).
```

That never happened when I was using Fedora and I have had `systemd.user.startServices` set to `true` for a very long time.

My home-manager configuration is using flakes and is public: https://github.com/DamienCassou/nix-system.

### System information

```markdown
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0-29-amd64, Debian GNU/Linux, 12 (bookworm), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.25.3`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by johnhamelink** [comment]
I just transplanted my configuration from one machine to another, and now I'm experiencing this issue on the new machine.

**Comment by DamienCassou** [comment]
> I just transplanted my configuration from one machine to another, and now I'm experiencing this issue on the new machine.

are you by any chance using [nh](https://github.com/viperML/nh)? I had a few problems and they disappeared more or less when I stopped using nh.

**Comment by johnhamelink** [comment]
I was using nh, but last night I was able to run `nh home switch -u` without the error showing up. I'm currently experiencing an unrelated build failure so until I've fixed that I can't check again!

**Comment by nilp0inter** [comment]
I am also experiencing this 2-3 weeks ago. I am running home-manager in NixOS as a module.

Error switching configurations:

```
sudo nixos-rebuild --flake . --accept-flake-config switch
[sudo] password for nil:
warning: Git tree '/home/nil/Projects/github.com/nilp0inter/nixos-config' is dirty
building the system configuration...
warning: Git tree '/home/nil/Projects/github.com/nilp0inter/nixos-config' is dirty
stopping the following units: accounts-daemon.service
NOT restarting the following changed units: libvirt-guests.service
activating the configuration...
sops-install-secrets: Imported /impermanence/persistent/etc/ssh/ssh_host_ed25519_key as age key with fingerprint age1jl7j9ehwn0q8kggx0ja34hygpcdax76va8xsc9ylfdshj3a0zfjqrcy6ct
setting up /etc...
sops-install-secrets: Imported /impermanence/persistent/etc/ssh/ssh_host_ed25519_key as age key with fingerprint age1jl7j9ehwn0q8kggx0ja34hygpcdax76va8xsc9ylfdshj3a0zfjqrcy6ct
reloading user units for nil...
restarting sysinit-reactivation.target
reloading the following units: dbus.service, firewall.service
restarting the following units: polkit.service, systemd-udevd.service
starting the following units: accounts-daemon.service
the following new units were started: libvirtd.service, NetworkManager-dispatcher.service, sysinit-reactivation.target, systemd-ask-password-console.path, systemd-tmpfiles-resetup.service
warning: the following units failed: home-manager-nil.service
× home-manager-nil.service - Home Manager environment for nil
     Loaded: loaded (/etc/systemd/system/home-manager-nil.service; enabled; preset: ignored)
     Active: failed (Result: exit-code) since Thu 2025-01-30 12:28:40 CET; 264ms ago
 Invocation: 34eed60f57f84040b9091da76249ff77
    Process: 63867 ExecStart=/nix/store/zwqi7z0mbisqrzrgr55sqlnrmfvc3w28-hm-setup-env /nix/store/5zhfgiggaqk0z23qhsaf25087dhdc8bi-home-manager-generation (code=exited, status=1/FAILURE)
   Main PID: 63867 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
         IO: 5.5M read, 0B written
   Mem peak: 30.5M
        CPU: 1.981s

ene 30 12:28:40 haku hm-activate-nil[64967]: Error: Error switching
ene 30 12:28:40 haku hm-activate-nil[64967]: Caused by:
ene 30 12:28:40 haku hm-activate-nil[64967]:     0: Failed to perform post-reload tasks
ene 30 12:28:40 haku hm-activate-nil[64967]:     1: Failed to start unit gpg-agent.service
ene 30 12:28:40 haku hm-activate-nil[64967]:     2: org.freedesktop.systemd1.OnlyByDependency: Operation refused, unit gpg-agent.service may be requested by dependency only (it is configured to refuse manual start/stop).
ene 30 12:28:40 haku hm-activate-nil[65014]: removed '/home/nil/.local/state/home-manager/gcroots/new-home'
ene 30 12:28:40 haku systemd[1]: home-manager-nil.service: Main process exited, code=exited, status=1/FAILURE
ene 30 12:28:40 haku systemd[1]: home-manager-nil.service: Failed with result 'exit-code'.
ene 30 12:28:40 haku systemd[1]: Failed to start Home Manager environment for nil.
ene 30 12:28:40 haku systemd[1]: home-manager-nil.service: Consumed 1.981s CPU time, 30.5M memory peak, 5.5M read from disk.
warning: error(s) occurred while switching to the new configuration
```

## System information
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.11, NixOS, 25.05 (Warbler), 25.05.20250124.825479c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - nixpkgs: `/nix/store/kmns8raz2za5ra55bnbj7srxrya3bild-source`
 ```

**Comment by nilp0inter** [comment]
I've been investigating this issue further and suspect it may be related to the recent integration of `sd-switch` from #5452, which was merged shortly before this problem first appeared. Specifically, it seems that `sd-switch` (still present in version 0.5.3) might not correctly identify or respect the `RefuseManualStart=true` setting in the `gpg-agent.service` unit. As a result, it attempts to manually stop and restart the service, causing the reported failure.

Perhaps @rycee could offer additional insights or guidance on this issue?

**Comment by hangtaip** [comment]
This happened to me too, when moving my config to another machine. 
I'm using home-manager on wsl2 with ubuntu.

First time, the error is no-pinentry. Then i run the default gnupg, before installing through home-manager.
But it failed to build because gpg-agent can't start manually.

Then, I added:
`RefuseManualStart = false` like this, reverse of what @nilp0inter said, and build successfully.

```nix
services.gpg-agent = {
        enable = true;
        pinentryPackage = pkgs.pinentry-curses;
        extraConfig = ''
            RefuseManualStart = false
        '';
    };
```

Then to use gpg, i commented it back because gpg can't connect to gpg-agent. This is the error i got without commenting them.
```zsh
gpg: error running '/nix/store/pggww1d2pg24fcg5v36xn63n53vanyyi-gnupg-2.4.7/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/nix/store/pggww1d2pg24fcg5v36xn63n53vanyyi-gnupg-2.4.7/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: error running '/nix/store/pggww1d2pg24fcg5v36xn63n53vanyyi-gnupg-2.4.7/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/nix/store/pggww1d2pg24fcg5v36xn63n53vanyyi-gnupg-2.4.7/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: keydb_search failed: No agent running
gpg: public key decryption failed: No secret key
gpg: decryption failed: No secret key
❌ Decryption failed: exit status 2
```

Even though it build successfully, i have some error shown.
```zsh
The user systemd session is degraded:
  UNIT                     LOAD   ACTIVE SUB    DESCRIPTION
● gpg-agent.service        loaded failed failed GnuPG cryptographic agent and passphrase cache
● gpg-agent-browser.socket loaded failed failed GnuPG cryptographic agent and passphrase cache (access for web browsers)
● gpg-agent-extra.socket   loaded failed failed GnuPG cryptographic agent and passphrase cache (restricted)
● gpg-agent-ssh.socket     loaded failed failed GnuPG cryptographic agent (ssh-agent emulation)
● gpg-agent.socket         loaded failed failed GnuPG cryptographic agent and passphrase cache

Legend: LOAD   → Reflects whether the unit definition was properly loaded.
        ACTIVE → The high-level unit activation state, i.e. generalization of SUB.
        SUB    → The low-level unit activation state, values depend on unit type.

5 loaded units listed.
Attempting to reload services anyway...
The service manager is degraded.
Failed services: gpg-agent-extra.socket, gpg-agent.service, gpg-agent.socket, gpg-agent-ssh.socket, gpg-agent-browser.socket
Attempting to continue anyway...
Starting units: gpg-agent.socket

There are 201 unread and relevant news items.
Read them by running the command "home-manager news".
```

Not sure is this the proper way or not.

**Comment by nilp0inter** [comment]
Hi @hangtaip, 

Just to clarify, RefuseManualStart is a setting for systemd units, not for gpg-agent configurations. I suspect the error you're encountering after changing that setting might be due to gpg-agent encountering an unknown option in its configuration file. 

I am still experiencing this issue and am unsure how to proceed with debugging it. I would greatly appreciate any guidance or suggestions.  

Thank you, and @rycee, if you have any insights, your expertise would be very helpful.
