### ISSUE TITLE
bug: Cannot send mails using msmtp

### ISSUE THREAD

**Issue by vbrandl** [nix-community/home-manager#8384]
### Are you following the right branch?

- [x] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Issue description

Sending mails using neomutt and msmtp fails with `msmtp: cannot use both --from and --read-envelope-from`. My generated neomutt configuration contains `set sendmail='msmtpq --read-envelope-from --read-recipients'`.

In `~/.config/msmtp/config`, I have:

```
...

account vbrandl
...
from my.email.address@example.com
```

I guess the problem appears because neomutt sets the `--read-envelope-from` flag and the msmtp config contains a `from` entry

I'm not exactly sure when this first occurred. It might be with the update to 25.11.

Edit: It actually looks like the mails are sent, but I don't get a copy in my `Sent` folder

### Maintainer CC

@KarlJoad 

### System information

```markdown
nix-shell -p nix-info --run "nix-info -m"
warning: Nix search path entry '/home/me/.nix-defexpr/channels' does not exist, ignoring
 - system: `"x86_64-linux"`
 - host os: `Linux 6.18.1, NixOS, 25.11 (Xantusia), 25.11.20251215.c6f52eb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.31.2`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/store/h804a5w2y4cqmzkrcgp37m8804ialqi4-source`
```

**Comment by ravenjoad** [comment]
@vbrandl, just to confirm, are the emails being sent? Do the intended recipients receive everything (message and attachments)?

Putting contents in the `Sent` folder is not typically the responsibility of msmtp. msmtp just takes a mail file and submits it to the SMTP server for sending/forwarding. Usually, the MUA (neomutt in your case) or upstream IMAP email provider must make put a copy of the sent mail in the `Sent` directory. I know that Gmail creates a copy of the sent mail and puts it in `Sent` when it handles SMTP for you. So your MUA needs to discard the message after sending and then do an IMAP sync with Gmail for the message to show up in `Sent`.

I use Emacs and mu4e as my MUA, mbsync/isync, and msmtp, and I have the below snippet of configuration for mu4e with Gmail.
```elisp
(use-package mu4e
  :ensure nil ; Provided by mu package
  :defer t
  ;; We can only load mu4e if mu was installed
  :when (and (executable-find "mu")
             (locate-library "mu4e")
             (executable-find "msmtp"))
  :load-path mu4e-load-path
  :custom
  ...
  ;; Moving messages (especially between directories) renames files to avoid
  ;; errors
  (mu4e-change-filenames-when-moving t)
  ;; When sending mail, delete the message file from "outgoing". If using Gmail,
  ;; messages are automatically moved to the Sent folder by Google. So, we don't
  ;; need to do anything on our end to preserve the fact we sent the message.
  (mu4e-sent-messages-behavior 'delete)
  ...)
```

In particular mu4e has this documentation for `mu4e-sent-messages-behavior`:
```
mu4e-sent-messages-behavior is a variable defined in ‘mu4e-draft.el’.

Its value is ‘delete’
Original value was ‘sent’

Determines what mu4e does with sent messages.

This is one of the symbols:
* ‘sent’    move the sent message to the Sent-folder (‘mu4e-sent-folder’)
* ‘trash’   move the sent message to the Trash-folder (‘mu4e-trash-folder’)
* ‘delete’  delete the sent message.

Note, when using GMail/IMAP, you should set this to either
‘trash’ or ‘delete’, since GMail already takes care of keeping
copies in the sent folder.
```

**Comment by vbrandl** [comment]
Yes, normally neomutt moves mails to the `sent` folder, when msmtp does not exit with an error code.

But due to the above error, the exit code seems to be != 0, therefore neomutt handles that as an error.

The mails are sent (also with attachments) but somehow the configuration is in a broken state, so msmtp complains about both flags being set

**Comment by ravenjoad** [comment]
The `--read-envelope-from` flag means that msmtp should choose which account from `msmtp/config` to use for options. But `-f`/`--from` explicitly states which account to use. You need to choose which one to use.

I also have the `--read-envelop-from` flag in my mu4e config, but I tell mu4e that `-f`/`--from` is "evil". You likely have to do the same. 
```elisp
(use-package mu4e
  ...
  :custom
  ...
  ;; Use a sendmail program rather than sending directly from Emacs
  (message-send-mail-function 'message-send-mail-with-sendmail)
  ;; Make msmtp infer the correct account to send from by the From: email address
  (message-sendmail-extra-arguments '("--read-envelope-from"))
  ;; Don't add "-f username" to the msmtp command.
  (message-sendmail-f-is-evil 't)
  ...)
```

neomutt must be doing something there. If you can, have neomutt log the exact command it is using. I bet neomutt is setting `--from` based on what context (that's what mu4e calls which "account" you are currently "in") or account you are composing from.

You will have to decide the behavior you want. The default behavior of the generated neomutt config when you have msmtp enabled is to use `--read-from-envelope`. https://nix-community.github.io/home-manager/options.xhtml
You could also change the `neomutt.sendMailCommand` string to remove the `--read-envelope-from` flag and have neomutt add `-f`/`--from` automatically.

**Comment by ravenjoad** [comment]
If you can, you should also try recreating these email sends with debugging/verbosity turned on/up. That will help us figure out if this is a config problem, a program problem, or something else.

**Comment by ravenjoad** [comment]
@vbrandl, is this still an issue?

**Comment by vbrandl** [comment]
Yes, but I haven't had time yet to extract the relevant parts of my config to reproduce. I'll post here once I did that

**Comment by rafaelrc7** [comment]
Hello, I also have this issue, and it is pretty annoying. Is there a way I can help to diagnose it?

**Comment by rafaelrc7** [comment]
Ok, I did some testing, it seems the problem is with `msmtpq` and not neomutt actually? I created the following file `mail`:
```
From: my@email.com
To: another@my.email
Subject: Test from term

Hello, world!
```
And ran: `msmtpq --read-envelope-from --read-recipients <mail` it showed the same output shown in neomutt:
```
  mail for [ --read-envelope-from --read-recipients ] : send was successful
msmtp: cannot use both --from and --read-envelope-from
  mail [ 1 ] [ 2023-12-16-15.47.04 ] from queue ; send failed ; msmtp rc = 64
```

The weird thing is that I tried manually editting `~/.config/msmtp/config` and removing the `from` entries, but the same "warning" is sent, so I'm at a loss. It seems the problem is in `msmtpq` and not neomutt, but I don't know how to fix it.

**Comment by rafaelrc7** [comment]
Sorry for the three comments in a row, but I believe I fixed the issue for myself, and considering my config similarities to @vbrandl, it's probably the same. It seems there were one or more "broken" (and old, notice my error msg on my previous comment, it mentions a 2023 message) e-mails inside my queue (`~/.local/share/msmtp/queue`) and it seems everytime I tried to send an e-mail, it tried to send everything in queue and failed for those broke ones. 

I believe in previous versions msmtpq failed silently about those old messages, but last year it started complaining about it, which in turn kind of broke neomutt, because while the newest message is sent successfully, neomutt interprets the error about the old message as a failure of the whole process (what does seem as bad behaviour from msmtpq imo, and maybe worth to open an issue about it upstream?).

I purged my queue with `msmtp-queue -a` (BEWARE, this deletes all messages in your queue) and now it all works fine.

**Comment by vbrandl** [comment]
Thank you @rafaelrc7. Looks like I had the same problem. I removed the old mails from the queue (maybe I could have tried re-sending them using `msmtp-queue -r`, but they were old and not important) and now everything works again.

I'm still not sure why this became a problem only now, since there were some messages from 2022 in the queue but yeah, that was the problem...
